### ISSUE TITLE
配置文件中，METHOD是干啥的？有啥作用

### ISSUE THREAD

**Issue by ccl-1** [Thinklab-SJTU/R3Det_Tensorflow#128]
你好，我想问一下，cfgs文件中的 METHOD是啥意思，理解为GT 标注框为水平 H， 旋转框为R 对吗？
我看源码显示，METHOD==‘H’，框的个数是ratio×scale，且位置回归（-1,4），后来拓展一维让角度angle=0,
当METHOD==‘R’，框的个数是ratio×scale×len(angle_range)，位置回归（-1,5）,这很旋转框。
但是，我看基本所有配置文件里面的 METHOD 都用的 ‘H’， 然后我用 这个训练得到的也是旋转目标， 那这里设置 METHOD 不是区分水平旋转的吗？他具体是干啥的？

我尝试过 METHOD==‘R’进行训练，但是报错。如下：
2021-04-02 12:32:15.047781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1
2021-04-02 12:32:15.625242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 12:32:15.625278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 
2021-04-02 12:32:15.625287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N N 
2021-04-02 12:32:15.625293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N 
2021-04-02 12:32:15.626314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9938 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
2021-04-02 12:32:15.626905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10281 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:81:00.0, compute capability: 7.5)
WARNING:tensorflow:From /media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py:314: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
restore model
2021-04-02 12:32:51.950834: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at where_op.cc:286 : Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 5887, status: invalid resource handle
2021-04-02 12:32:53.880663: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881067: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881113: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881193: W tensorflow/core/kernels/queue_base.cc:277] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881642: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881699: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881745: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.881886: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882204: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882226: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882240: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882312: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882360: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.882398: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.884765: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.884788: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-04-02 12:32:53.884801: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 5887, status: invalid resource handle
	 [[{{node tower_1/build_loss/Where_1}}]]
	 [[{{node tower_1/clip_by_norm_14/truediv}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py", line 374, in <module>
    train()
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py", line 353, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 5887, status: invalid resource handle
	 [[node tower_1/build_loss/Where_1 (defined at /media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/libs/losses/losses.py:36) ]]
	 [[node tower_1/clip_by_norm_14/truediv (defined at /media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py:263) ]]

Caused by op 'tower_1/build_loss/Where_1', defined at:
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py", line 374, in <module>
    train()
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py", line 223, in train
    gpu_id=i)
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/libs/networks/build_whole_network_r3det.py", line 320, in build_whole_detection_network
    cls_loss = losses.focal_loss(labels, rpn_cls_score, anchor_states)
  File "/media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/libs/losses/losses.py", line 36, in focal_loss
    indices = tf.reshape(tf.where(tf.not_equal(anchor_state, -1)), [-1, ])
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 3202, in where
    return gen_array_ops.where(condition=condition, name=name)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 11050, in where
    "Where", input=condition, name=name)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/conda-env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 5887, status: invalid resource handle
	 [[node tower_1/build_loss/Where_1 (defined at /media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/libs/losses/losses.py:36) ]]
	 [[node tower_1/clip_by_norm_14/truediv (defined at /media/ubuntu/程序+数据集/chenchenglin/R3Det_Tensorflow/tools/multi_gpu_train_r3det.py:263) ]]

大佬，求回复。

**Comment by yangxue0827** [comment]
这个指的是使用旋转anchor还是水平anchor，最后预测结果都是旋转框，建议用H

**Comment by yangxue0827** [comment]
你这个问题可能是tf版本的问题，或者是R模式会设置很多anchoe，你的显存不够用
