### ISSUE TITLE
I have problems training with my own data. 

### ISSUE THREAD

**Issue by lyccol** [Thinklab-SJTU/R3Det_Tensorflow#131]
………………Normal training …………
************************************************************
2021-06-15 22:50:38: global_step:20920  current_step:20920
per_cost_time:0.402s
cls_loss:0.534
reg_loss:0.548
refine_cls_loss:0.658
refine_reg_loss:0.347
refine_cls_loss_stage3:0.000
refine_reg_loss_stage3:0.000
total_losses:2.087

************************************************************
2021-06-15 22:50:58: global_step:20960  current_step:20960
per_cost_time:0.442s
cls_loss:0.374
reg_loss:0.572
refine_cls_loss:0.441
refine_reg_loss:0.372
refine_cls_loss_stage3:0.000
refine_reg_loss_stage3:0.000
total_losses:1.758

2021-06-15 22:51:17.541334: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: KeyError: 5
Traceback (most recent call last):

  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/box_utils/draw_box_in_img.py", line 235, in draw_boxes_with_label_and_scores
    draw_label_with_scores(draw_obj, box, a_label, a_score, color='White')

  File "../libs/box_utils/draw_box_in_img.py", line 153, in draw_label_with_scores
    txt = LABEL_NAME_MAP[label] + ':' + str(round(score, 2))

KeyError: 5

2021-06-15 22:51:17.956001: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956413: W tensorflow/core/kernels/queue_base.cc:277] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956520: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956622: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956698: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956725: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956809: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956831: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956849: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956878: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956918: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956939: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956957: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.956976: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.957026: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.957051: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2021-06-15 22:51:17.957071: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: KeyError: 5
Traceback (most recent call last):

  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/box_utils/draw_box_in_img.py", line 235, in draw_boxes_with_label_and_scores
    draw_label_with_scores(draw_obj, box, a_label, a_score, color='White')

  File "../libs/box_utils/draw_box_in_img.py", line 153, in draw_label_with_scores
    txt = LABEL_NAME_MAP[label] + ':' + str(round(score, 2))

KeyError: 5

	 [[{{node tower_1/PyFunc_3}}]]
	 [[{{node tower_1/Reshape_6/tensor}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_gpu_train_r3det.py", line 373, in <module>
    train()
  File "multi_gpu_train_r3det.py", line 352, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: KeyError: 5
Traceback (most recent call last):

  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/box_utils/draw_box_in_img.py", line 235, in draw_boxes_with_label_and_scores
    draw_label_with_scores(draw_obj, box, a_label, a_score, color='White')

  File "../libs/box_utils/draw_box_in_img.py", line 153, in draw_label_with_scores
    txt = LABEL_NAME_MAP[label] + ':' + str(round(score, 2))

KeyError: 5

	 [[node tower_1/PyFunc_3 (defined at ../libs/box_utils/show_box_in_tensor.py:79) ]]
	 [[node tower_1/Reshape_6/tensor (defined at ../libs/box_utils/show_box_in_tensor.py:80) ]]

Caused by op 'tower_1/PyFunc_3', defined at:
  File "multi_gpu_train_r3det.py", line 373, in <module>
    train()
  File "multi_gpu_train_r3det.py", line 240, in train
    method=1)
  File "../libs/box_utils/show_box_in_tensor.py", line 79, in draw_boxes_with_categories_and_scores
    Tout=[tf.uint8])
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 468, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 282, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 151, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): KeyError: 5
Traceback (most recent call last):

  File "/tank/newhome/deserts/anaconda3/envs/torch13/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/box_utils/draw_box_in_img.py", line 235, in draw_boxes_with_label_and_scores
    draw_label_with_scores(draw_obj, box, a_label, a_score, color='White')

  File "../libs/box_utils/draw_box_in_img.py", line 153, in draw_label_with_scores
    txt = LABEL_NAME_MAP[label] + ':' + str(round(score, 2))

KeyError: 5

	 [[node tower_1/PyFunc_3 (defined at ../libs/box_utils/show_box_in_tensor.py:79) ]]
	 [[node tower_1/Reshape_6/tensor (defined at ../libs/box_utils/show_box_in_tensor.py:80) ]]

**Comment by yangxue0827** [comment]
label_dict修改有误吧，预测出第五类，但是在你的 LABEL_NAME_MAP[label]里没有
