### ISSUE TITLE
 IndexError: Out of bounds on buffer access (axis 0)

### ISSUE THREAD

**Issue by piaoliuping123** [Thinklab-SJTU/R3Det_Tensorflow#18]
您好，很感谢能看到您的论文，在MODEL_ZOO.md.下载模型测试，报错，谢谢
File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)

2020-04-02 15:56:01.255092: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: Out of bounds on buffer access (axis 0)
Traceback (most recent call last):

  File "/home/yongfeng/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)

2020-04-02 15:56:01.255216: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: Out of bounds on buffer access (axis 0)
Traceback (most recent call last):

  File "/home/yongfeng/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)

2020-04-02 15:56:01.255469: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: Out of bounds on buffer access (axis 0)
Traceback (most recent call last):

  File "/home/yongfeng/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)

2020-04-02 15:56:01.256507: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: Out of bounds on buffer access (axis 0)
Traceback (most recent call last):

  File "/home/yongfeng/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)

2020-04-02 15:56:01.257749: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: IndexError: Out of bounds on buffer access (axis 0)
Traceback (most recent call last):

  File "/home/yongfeng/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)

IndexError: Out of bounds on buffer access (axis 0)，

请问这是啥原因呢，谢谢！

**Comment by piaoliuping123** [comment]
refine_proposal_opr.py文件  nms_indices = nms_rotate.nms_rotate(decode_boxes=filtered_boxes,
                                            scores=filtered_scores,
                                            iou_threshold=cfgs.NMS_IOU_THRESHOLD,
                                            max_output_size=100,
                                            use_angle_condition=False,
                                            angle_threshold=15,
                                            use_gpu=False)
 在cpu模式下，use_gpu=False就可以编译通过,
在gpu 模式下，use_gpu=True运行报错File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms (rotate_polygon_nms.cpp:1874)
IndexError: Out of bounds on buffer access (axis 0)，
运行命令为：python3 inference.py --data_dir=images/ --save_dir=result/ --gpu=0
cfg文件为：cfgs_res50_dota_r3det_v2.py
模型也是在MODEL_ZOO.md中下载的，希望能够得到大家的帮助,谢谢！

**Comment by piaoliuping123** [comment]
调试发现，在nms_rotate.py文件中，
def nms_rotate_gpu(boxes_list, scores, iou_threshold, use_angle_condition=False, angle_gap_threshold=0, device_id=0):
    if use_angle_condition:
        x_c, y_c, w, h, theta = tf.unstack(boxes_list, axis=1)
        boxes_list = tf.transpose(tf.stack([x_c, y_c, w, h, theta]))
        det_tensor = tf.concat([boxes_list, tf.expand_dims(scores, axis=1)], axis=1)
        keep = tf.py_func(rotate_gpu_nms,
                          inp=[det_tensor, iou_threshold, device_id],
                          Tout=tf.int64)
        return keep
    else:
        x_c, y_c, w, h, theta = tf.unstack(boxes_list, axis=1)
        boxes_list = tf.transpose(tf.stack([x_c, y_c, w, h, theta]))
        det_tensor = tf.concat([boxes_list, tf.expand_dims(scores, axis=1)], axis=1)
        keep = tf.py_func(rotate_gpu_nms,
                          inp=[det_tensor, iou_threshold, device_id],
                          Tout=tf.int64)
        keep = tf.reshape(keep, [-1])
        return keep
这个函数中的 keep = tf.py_func(rotate_gpu_nms,
                          inp=[det_tensor, iou_threshold, device_id],
                          Tout=tf.int64)语句报错

**Comment by yangxue0827** [comment]
使用cpu的nms吧 @piaoliuping123
