### ISSUE TITLE
测试模型出现问题

### ISSUE THREAD

**Issue by huyu6789** [Thinklab-SJTU/R3Det_Tensorflow#77]
你好，我在按照您教程的步骤进行运行时，到eval步骤出现了如下问题
![1](https://user-images.githubusercontent.com/46044800/95840627-f6a14c00-0d76-11eb-8b23-fc6f85980efa.png)
*****************************************************************************************************************************
root@ca701139e0de:/usr/downloads/R3Det_Tensorflow-master/tools# python test_dota_r3det_ms.py --test_dir='/PATH/TO/IMAGES/' --gpus=0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_dota_r3det_ms.py", line 9, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
root@ca701139e0de:/usr/downloads/R3Det_Tensorflow-master/tools#
*****************************************************************************************************************************
这应该是环境问题，但是我是在您的docker环境下运行的，请问这种问题怎么解决呢。
(导致出现这个错误的命令为 python test_dota_r3det_ms.py --test_dir='/PATH/TO/IMAGES/' --gpus=0 -s)

**Comment by yangxue0827** [comment]
用的nvidia-docker启动的容器吗 @huyu6789

**Comment by huyu6789** [comment]
> 用的nvidia-docker启动的容器吗 @huyu6789
不是，就是用的docker，难道说是要用nvidia-docker才行？

**Comment by huyu6789** [comment]
> 用的nvidia-docker启动的容器吗 @huyu6789
不是，就是用的docker，难道说是要用nvidia-docker才行？

**Comment by yangxue0827** [comment]
应该是的，你试试 @huyu6789

**Comment by huyu6789** [comment]
> 应该是的，你试试 @huyu6789

好嘞，谢谢指导~

**Comment by huyu6789** [comment]
谢谢作者，使用nvidia-docker已经解决问题，现在有一个小小的疑问是，我用一张图片测试完成后，要在哪里可以看到效果呢，代码中好像也没有明确的说明。
![Uploading 2.png…]()

**Comment by huyu6789** [comment]
谢谢作者，使用nvidia-docker已经解决问题，现在有一个小小的疑问是，我用一张图片测试完成后，要在哪里可以看到效果呢，代码中好像也没有明确的说明
![2](https://user-images.githubusercontent.com/46044800/95968165-b528a380-0e3f-11eb-812c-57933db51711.png)

**Comment by yangxue0827** [comment]
tools/test_dota/***,你搜一下测试脚本的保存的命令不就知道了 @huyu6789

**Comment by huyu6789** [comment]
> tools/test_dota/***,你搜一下测试脚本的保存的命令不就知道了 @huyu6789

谢谢，我在test_dota中找到了测试后的图片，同样我出现了issues中别人出现过的问题--测试后的图片和输入图片一样(没有检测框),你有回答说是只使用了预训练权重的原因，请问如果我想输出测试框，在哪里能够下载到你所训练好的权重呢？

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/96001079-385eef00-0e6a-11eb-8f49-1e7f9d3ff12c.png)
README里有给链接 @huyu6789

**Comment by huyu6789** [comment]
> ![image](https://user-images.githubusercontent.com/29257168/96001079-385eef00-0e6a-11eb-8f49-1e7f9d3ff12c.png)
> README里有给链接 @huyu6789

确实是这个问题，已经解决，感谢指导~
