### ISSUE TITLE
用docker 报错： ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

### ISSUE THREAD

**Issue by gftd** [Thinklab-SJTU/R3Det_Tensorflow#78]
>>> import tensorflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

During handling of the above exception, another exception occurred:

是不是启动容器时候需要一些特殊参数啊？
我的docker 容器启动方式：
docker run -it f2808fb1dfe9 bash

**Comment by yangxue0827** [comment]
要用nvidia-docker命令吧 @gftd
